trigger:
- main

stages:
  - stage: check_CONDA
    dependsOn: []
    jobs:
    - job:
      strategy:
        matrix:
          latest:
            image: macos-latest
          macos15:
            image: macos-15
          macos14:
            image: macos-14
          macos13:
            image: macos-13
          macos12:
            image: macos-12

      pool:
        vmImage: $(image)

      steps:
        - bash: |
            echo "USER=\"${USER}\""
            echo "CONDA=\"${CONDA}\""
          displayName: Check environment variables

        - bash: |
            stat /usr/local/miniconda
            ls -l /usr/local/miniconda
          displayName: Check for miniconda

        - bash: echo "##vso[task.prependpath]$CONDA/bin"
          displayName: Add conda to PATH

        # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
        # We need to take ownership if we want to update conda or install packages globally
        - bash: sudo chown -R $USER $CONDA
          displayName: Take ownership of conda installation
